package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Amb generated by hbm2java
 */
@Entity
@Table(name = "AMB")
public class Amb implements java.io.Serializable {

	private AmbId id;
	private String nome;
	private boolean FAutorizacaoPrevia;
	private boolean FAutorizadaAtendente;
	private boolean FRegulamentar;
	private boolean FPossivelCotacao;
	private Short idClassificacaoAmb;
	private Short idSubClassificacaoAmb;
	private Short idadeMinima;
	private Short idadeMaxima;
	private Character DSexoValido;
	private Short quantidadePermitidaNaVida;
	private Short quantidadeAuxiliares;
	private Short incidencia;
	private Double custoOperacionalCh;
	private Double honorarioMedicoCh;
	private short quantidadeProcedimentosGuia;
	private Short limiteSessoesRegulamentar;
	private Byte idPorteAnestesico;
	private Short idPorteCirurgico;
	private Integer idAmbGrupo;
	private Date timestamp;
	private Short idDescricaoExtrato;
	private Character DConsultaAnual;
	private Character DOpm;
	private Character DProcedimento;
	private Character DPeriodoAmb;
	private Integer idClassificacaoProcedimento;

	public Amb() {
	}

	public Amb(String nome, boolean FAutorizacaoPrevia, boolean FAutorizadaAtendente, boolean FRegulamentar,
			boolean FPossivelCotacao, short quantidadeProcedimentosGuia, Date timestamp) {
		this.nome = nome;
		this.FAutorizacaoPrevia = FAutorizacaoPrevia;
		this.FAutorizadaAtendente = FAutorizadaAtendente;
		this.FRegulamentar = FRegulamentar;
		this.FPossivelCotacao = FPossivelCotacao;
		this.quantidadeProcedimentosGuia = quantidadeProcedimentosGuia;
		this.timestamp = timestamp;
	}

	public Amb(Amb amb, String nome, boolean FAutorizacaoPrevia, boolean FAutorizadaAtendente, boolean FRegulamentar,
			boolean FPossivelCotacao, Short idClassificacaoAmb, Short idSubClassificacaoAmb, Short idadeMinima,
			Short idadeMaxima, Character DSexoValido, Short quantidadePermitidaNaVida, Short quantidadeAuxiliares,
			Short incidencia, Double custoOperacionalCh, Double honorarioMedicoCh, short quantidadeProcedimentosGuia,
			Short limiteSessoesRegulamentar, Byte idPorteAnestesico, Short idPorteCirurgico, Integer idAmbGrupo,
			Date timestamp, Short idDescricaoExtrato, Character DConsultaAnual, Character DOpm, Character DProcedimento,
			Character DPeriodoAmb, Integer idClassificacaoProcedimento) {
		this.nome = nome;
		this.FAutorizacaoPrevia = FAutorizacaoPrevia;
		this.FAutorizadaAtendente = FAutorizadaAtendente;
		this.FRegulamentar = FRegulamentar;
		this.FPossivelCotacao = FPossivelCotacao;
		this.idClassificacaoAmb = idClassificacaoAmb;
		this.idSubClassificacaoAmb = idSubClassificacaoAmb;
		this.idadeMinima = idadeMinima;
		this.idadeMaxima = idadeMaxima;
		this.DSexoValido = DSexoValido;
		this.quantidadePermitidaNaVida = quantidadePermitidaNaVida;
		this.quantidadeAuxiliares = quantidadeAuxiliares;
		this.incidencia = incidencia;
		this.custoOperacionalCh = custoOperacionalCh;
		this.honorarioMedicoCh = honorarioMedicoCh;
		this.quantidadeProcedimentosGuia = quantidadeProcedimentosGuia;
		this.limiteSessoesRegulamentar = limiteSessoesRegulamentar;
		this.idPorteAnestesico = idPorteAnestesico;
		this.idPorteCirurgico = idPorteCirurgico;
		this.idAmbGrupo = idAmbGrupo;
		this.timestamp = timestamp;
		this.idDescricaoExtrato = idDescricaoExtrato;
		this.DConsultaAnual = DConsultaAnual;
		this.DOpm = DOpm;
		this.DProcedimento = DProcedimento;
		this.DPeriodoAmb = DPeriodoAmb;
		this.idClassificacaoProcedimento = idClassificacaoProcedimento;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idAmb", column = @Column(name = "id_amb", nullable = false)),
			@AttributeOverride(name = "idTipoTabela", column = @Column(name = "id_tipo_tabela", nullable = false)) })
	public AmbId getId() {
		return this.id;
	}

	public void setId(AmbId id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 1024)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "f_autorizacao_previa", nullable = false)
	public boolean isFAutorizacaoPrevia() {
		return this.FAutorizacaoPrevia;
	}

	public void setFAutorizacaoPrevia(boolean FAutorizacaoPrevia) {
		this.FAutorizacaoPrevia = FAutorizacaoPrevia;
	}

	@Column(name = "f_autorizada_atendente", nullable = false)
	public boolean isFAutorizadaAtendente() {
		return this.FAutorizadaAtendente;
	}

	public void setFAutorizadaAtendente(boolean FAutorizadaAtendente) {
		this.FAutorizadaAtendente = FAutorizadaAtendente;
	}

	@Column(name = "f_regulamentar", nullable = false)
	public boolean isFRegulamentar() {
		return this.FRegulamentar;
	}

	public void setFRegulamentar(boolean FRegulamentar) {
		this.FRegulamentar = FRegulamentar;
	}

	@Column(name = "f_possivel_cotacao", nullable = false)
	public boolean isFPossivelCotacao() {
		return this.FPossivelCotacao;
	}

	public void setFPossivelCotacao(boolean FPossivelCotacao) {
		this.FPossivelCotacao = FPossivelCotacao;
	}

	@Column(name = "id_classificacao_amb")
	public Short getIdClassificacaoAmb() {
		return this.idClassificacaoAmb;
	}

	public void setIdClassificacaoAmb(Short idClassificacaoAmb) {
		this.idClassificacaoAmb = idClassificacaoAmb;
	}

	@Column(name = "id_sub_classificacao_amb")
	public Short getIdSubClassificacaoAmb() {
		return this.idSubClassificacaoAmb;
	}

	public void setIdSubClassificacaoAmb(Short idSubClassificacaoAmb) {
		this.idSubClassificacaoAmb = idSubClassificacaoAmb;
	}

	@Column(name = "idade_minima")
	public Short getIdadeMinima() {
		return this.idadeMinima;
	}

	public void setIdadeMinima(Short idadeMinima) {
		this.idadeMinima = idadeMinima;
	}

	@Column(name = "idade_maxima")
	public Short getIdadeMaxima() {
		return this.idadeMaxima;
	}

	public void setIdadeMaxima(Short idadeMaxima) {
		this.idadeMaxima = idadeMaxima;
	}

	@Column(name = "d_sexo_valido", length = 1)
	public Character getDSexoValido() {
		return this.DSexoValido;
	}

	public void setDSexoValido(Character DSexoValido) {
		this.DSexoValido = DSexoValido;
	}

	@Column(name = "quantidade_permitida_na_vida")
	public Short getQuantidadePermitidaNaVida() {
		return this.quantidadePermitidaNaVida;
	}

	public void setQuantidadePermitidaNaVida(Short quantidadePermitidaNaVida) {
		this.quantidadePermitidaNaVida = quantidadePermitidaNaVida;
	}

	@Column(name = "quantidade_auxiliares")
	public Short getQuantidadeAuxiliares() {
		return this.quantidadeAuxiliares;
	}

	public void setQuantidadeAuxiliares(Short quantidadeAuxiliares) {
		this.quantidadeAuxiliares = quantidadeAuxiliares;
	}

	@Column(name = "incidencia")
	public Short getIncidencia() {
		return this.incidencia;
	}

	public void setIncidencia(Short incidencia) {
		this.incidencia = incidencia;
	}

	@Column(name = "custo_operacional_ch", precision = 53, scale = 0)
	public Double getCustoOperacionalCh() {
		return this.custoOperacionalCh;
	}

	public void setCustoOperacionalCh(Double custoOperacionalCh) {
		this.custoOperacionalCh = custoOperacionalCh;
	}

	@Column(name = "honorario_medico_ch", precision = 53, scale = 0)
	public Double getHonorarioMedicoCh() {
		return this.honorarioMedicoCh;
	}

	public void setHonorarioMedicoCh(Double honorarioMedicoCh) {
		this.honorarioMedicoCh = honorarioMedicoCh;
	}

	@Column(name = "quantidade_procedimentos_guia", nullable = false)
	public short getQuantidadeProcedimentosGuia() {
		return this.quantidadeProcedimentosGuia;
	}

	public void setQuantidadeProcedimentosGuia(short quantidadeProcedimentosGuia) {
		this.quantidadeProcedimentosGuia = quantidadeProcedimentosGuia;
	}

	@Column(name = "limite_sessoes_regulamentar")
	public Short getLimiteSessoesRegulamentar() {
		return this.limiteSessoesRegulamentar;
	}

	public void setLimiteSessoesRegulamentar(Short limiteSessoesRegulamentar) {
		this.limiteSessoesRegulamentar = limiteSessoesRegulamentar;
	}

	@Column(name = "id_porte_anestesico")
	public Byte getIdPorteAnestesico() {
		return this.idPorteAnestesico;
	}

	public void setIdPorteAnestesico(Byte idPorteAnestesico) {
		this.idPorteAnestesico = idPorteAnestesico;
	}

	@Column(name = "id_porte_cirurgico")
	public Short getIdPorteCirurgico() {
		return this.idPorteCirurgico;
	}

	public void setIdPorteCirurgico(Short idPorteCirurgico) {
		this.idPorteCirurgico = idPorteCirurgico;
	}

	@Column(name = "id_amb_grupo")
	public Integer getIdAmbGrupo() {
		return this.idAmbGrupo;
	}

	public void setIdAmbGrupo(Integer idAmbGrupo) {
		this.idAmbGrupo = idAmbGrupo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "id_descricao_extrato")
	public Short getIdDescricaoExtrato() {
		return this.idDescricaoExtrato;
	}

	public void setIdDescricaoExtrato(Short idDescricaoExtrato) {
		this.idDescricaoExtrato = idDescricaoExtrato;
	}

	@Column(name = "d_consulta_anual", length = 1)
	public Character getDConsultaAnual() {
		return this.DConsultaAnual;
	}

	public void setDConsultaAnual(Character DConsultaAnual) {
		this.DConsultaAnual = DConsultaAnual;
	}

	@Column(name = "d_opm", length = 1)
	public Character getDOpm() {
		return this.DOpm;
	}

	public void setDOpm(Character DOpm) {
		this.DOpm = DOpm;
	}

	@Column(name = "d_procedimento", length = 1)
	public Character getDProcedimento() {
		return this.DProcedimento;
	}

	public void setDProcedimento(Character DProcedimento) {
		this.DProcedimento = DProcedimento;
	}

	@Column(name = "d_periodo_amb", length = 1)
	public Character getDPeriodoAmb() {
		return this.DPeriodoAmb;
	}

	public void setDPeriodoAmb(Character DPeriodoAmb) {
		this.DPeriodoAmb = DPeriodoAmb;
	}

	@Column(name = "id_classificacao_procedimento")
	public Integer getIdClassificacaoProcedimento() {
		return this.idClassificacaoProcedimento;
	}

	public void setIdClassificacaoProcedimento(Integer idClassificacaoProcedimento) {
		this.idClassificacaoProcedimento = idClassificacaoProcedimento;
	}

	@Override
	public String toString() {
		return "Amb [id=" + id + ", nome=" + nome + ", FAutorizacaoPrevia=" + FAutorizacaoPrevia
				+ ", FAutorizadaAtendente=" + FAutorizadaAtendente + ", FRegulamentar=" + FRegulamentar
				+ ", FPossivelCotacao=" + FPossivelCotacao + ", idClassificacaoAmb=" + idClassificacaoAmb
				+ ", idSubClassificacaoAmb=" + idSubClassificacaoAmb + ", idadeMinima=" + idadeMinima + ", idadeMaxima="
				+ idadeMaxima + ", DSexoValido=" + DSexoValido + ", quantidadePermitidaNaVida="
				+ quantidadePermitidaNaVida + ", quantidadeAuxiliares=" + quantidadeAuxiliares + ", incidencia="
				+ incidencia + ", custoOperacionalCh=" + custoOperacionalCh + ", honorarioMedicoCh=" + honorarioMedicoCh
				+ ", quantidadeProcedimentosGuia=" + quantidadeProcedimentosGuia + ", limiteSessoesRegulamentar="
				+ limiteSessoesRegulamentar + ", idPorteAnestesico=" + idPorteAnestesico + ", idPorteCirurgico="
				+ idPorteCirurgico + ", idAmbGrupo=" + idAmbGrupo + ", timestamp=" + timestamp + ", idDescricaoExtrato="
				+ idDescricaoExtrato + ", DConsultaAnual=" + DConsultaAnual + ", DOpm=" + DOpm + ", DProcedimento="
				+ DProcedimento + ", DPeriodoAmb=" + DPeriodoAmb + ", idClassificacaoProcedimento="
				+ idClassificacaoProcedimento + "]";
	}

}
