package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CancelamentoCarteira generated by hbm2java
 */
@Entity
@Table(name = "CANCELAMENTO_CARTEIRA", schema = "dbo", catalog = "CacDb")
public class CancelamentoCarteira implements java.io.Serializable {

	private CancelamentoCarteiraId id;
	private EmissaoCarteira emissaoCarteira;
	private short idMotivoCancelamento;
	private Date dthrCancelamento;
	private boolean FCarteiraDevolvida;
	private short idUsuario;
	private Date timestamp;

	public CancelamentoCarteira() {
	}

	public CancelamentoCarteira(EmissaoCarteira emissaoCarteira, short idMotivoCancelamento, Date dthrCancelamento,
			boolean FCarteiraDevolvida, short idUsuario, Date timestamp) {
		this.emissaoCarteira = emissaoCarteira;
		this.idMotivoCancelamento = idMotivoCancelamento;
		this.dthrCancelamento = dthrCancelamento;
		this.FCarteiraDevolvida = FCarteiraDevolvida;
		this.idUsuario = idUsuario;
		this.timestamp = timestamp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "numeroCarteira", column = @Column(name = "numero_carteira", nullable = false, precision = 17, scale = 0)),
			@AttributeOverride(name = "dv", column = @Column(name = "dv", nullable = false)) })
	public CancelamentoCarteiraId getId() {
		return this.id;
	}

	public void setId(CancelamentoCarteiraId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public EmissaoCarteira getEmissaoCarteira() {
		return this.emissaoCarteira;
	}

	public void setEmissaoCarteira(EmissaoCarteira emissaoCarteira) {
		this.emissaoCarteira = emissaoCarteira;
	}

	@Column(name = "id_motivo_cancelamento", nullable = false)
	public short getIdMotivoCancelamento() {
		return this.idMotivoCancelamento;
	}

	public void setIdMotivoCancelamento(short idMotivoCancelamento) {
		this.idMotivoCancelamento = idMotivoCancelamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_cancelamento", nullable = false, length = 23)
	public Date getDthrCancelamento() {
		return this.dthrCancelamento;
	}

	public void setDthrCancelamento(Date dthrCancelamento) {
		this.dthrCancelamento = dthrCancelamento;
	}

	@Column(name = "f_carteira_devolvida", nullable = false)
	public boolean isFCarteiraDevolvida() {
		return this.FCarteiraDevolvida;
	}

	public void setFCarteiraDevolvida(boolean FCarteiraDevolvida) {
		this.FCarteiraDevolvida = FCarteiraDevolvida;
	}

	@Column(name = "id_usuario", nullable = false)
	public short getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(short idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

}
