package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CgDiariaGasTaxaId generated by hbm2java
 */
@Embeddable
public class CgDiariaGasTaxaId implements java.io.Serializable {

	private int idDiariaGasTaxa;
	private int idTipoTabela;

	public CgDiariaGasTaxaId() {
	}

	public CgDiariaGasTaxaId(int idDiariaGasTaxa, int idTipoTabela) {
		this.idDiariaGasTaxa = idDiariaGasTaxa;
		this.idTipoTabela = idTipoTabela;
	}

	@Column(name = "id_diaria_gas_taxa", nullable = false)
	public int getIdDiariaGasTaxa() {
		return this.idDiariaGasTaxa;
	}

	public void setIdDiariaGasTaxa(int idDiariaGasTaxa) {
		this.idDiariaGasTaxa = idDiariaGasTaxa;
	}

	@Column(name = "id_tipo_tabela", nullable = false)
	public int getIdTipoTabela() {
		return this.idTipoTabela;
	}

	public void setIdTipoTabela(int idTipoTabela) {
		this.idTipoTabela = idTipoTabela;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CgDiariaGasTaxaId))
			return false;
		CgDiariaGasTaxaId castOther = (CgDiariaGasTaxaId) other;

		return (this.getIdDiariaGasTaxa() == castOther.getIdDiariaGasTaxa())
				&& (this.getIdTipoTabela() == castOther.getIdTipoTabela());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDiariaGasTaxa();
		result = 37 * result + this.getIdTipoTabela();
		return result;
	}

}
