package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CgMedicamento generated by hbm2java
 */
@Entity
@Table(name = "CG_MEDICAMENTO")
public class CgMedicamento implements java.io.Serializable {

	private int idMedicamento;
	private int idMedicamentoAns;
	private int idTipoTabela;
	private String descricao;
	private String apresentacao;
	private String laboratorio;
	private Date dtInicio;
	private Date dtFim;
	private Date timestamp;

	public CgMedicamento() {
	}

	public CgMedicamento(int idMedicamento, int idMedicamentoAns, int idTipoTabela, String descricao,
			String apresentacao, String laboratorio, Date dtInicio, Date timestamp) {
		this.idMedicamento = idMedicamento;
		this.idMedicamentoAns = idMedicamentoAns;
		this.idTipoTabela = idTipoTabela;
		this.descricao = descricao;
		this.apresentacao = apresentacao;
		this.laboratorio = laboratorio;
		this.dtInicio = dtInicio;
		this.timestamp = timestamp;
	}

	public CgMedicamento(int idMedicamento, int idMedicamentoAns, int idTipoTabela, String descricao,
			String apresentacao, String laboratorio, Date dtInicio, Date dtFim, Date timestamp) {
		this.idMedicamento = idMedicamento;
		this.idMedicamentoAns = idMedicamentoAns;
		this.idTipoTabela = idTipoTabela;
		this.descricao = descricao;
		this.apresentacao = apresentacao;
		this.laboratorio = laboratorio;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
		this.timestamp = timestamp;
	}

	@Id

	@Column(name = "id_medicamento", unique = true, nullable = false)
	public int getIdMedicamento() {
		return this.idMedicamento;
	}

	public void setIdMedicamento(int idMedicamento) {
		this.idMedicamento = idMedicamento;
	}

	@Column(name = "id_medicamento_ans", nullable = false)
	public int getIdMedicamentoAns() {
		return this.idMedicamentoAns;
	}

	public void setIdMedicamentoAns(int idMedicamentoAns) {
		this.idMedicamentoAns = idMedicamentoAns;
	}

	@Column(name = "id_tipo_tabela", nullable = false)
	public int getIdTipoTabela() {
		return this.idTipoTabela;
	}

	public void setIdTipoTabela(int idTipoTabela) {
		this.idTipoTabela = idTipoTabela;
	}

	@Column(name = "descricao", nullable = false, length = 150)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "apresentacao", nullable = false, length = 160)
	public String getApresentacao() {
		return this.apresentacao;
	}

	public void setApresentacao(String apresentacao) {
		this.apresentacao = apresentacao;
	}

	@Column(name = "laboratorio", nullable = false, length = 150)
	public String getLaboratorio() {
		return this.laboratorio;
	}

	public void setLaboratorio(String laboratorio) {
		this.laboratorio = laboratorio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_inicio", nullable = false, length = 10)
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_fim", length = 10)
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

}
