package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CgSimproInicial generated by hbm2java
 */
@Entity
@Table(name = "CG_SIMPRO_INICIAL", schema = "dbo", catalog = "CacDb")
public class CgSimproInicial implements java.io.Serializable {

	private CgSimproInicialId id;

	public CgSimproInicial() {
	}

	public CgSimproInicial(CgSimproInicialId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cdUsuario", column = @Column(name = "cd_usuario", length = 15)),
			@AttributeOverride(name = "cdFracao", column = @Column(name = "cd_fracao", length = 15)),
			@AttributeOverride(name = "descricao", column = @Column(name = "descricao", length = 100)),
			@AttributeOverride(name = "vigencia", column = @Column(name = "vigencia", length = 10)),
			@AttributeOverride(name = "identif", column = @Column(name = "identif", length = 1)),
			@AttributeOverride(name = "pcEmFab", column = @Column(name = "pc_em_fab", precision = 53, scale = 0)),
			@AttributeOverride(name = "pcEmVen", column = @Column(name = "pc_em_ven", precision = 53, scale = 0)),
			@AttributeOverride(name = "pcEmUsu", column = @Column(name = "pc_em_usu", precision = 53, scale = 0)),
			@AttributeOverride(name = "pcFrFab", column = @Column(name = "pc_fr_fab", precision = 53, scale = 0)),
			@AttributeOverride(name = "pcFrVen", column = @Column(name = "pc_fr_ven", precision = 53, scale = 0)),
			@AttributeOverride(name = "pcFrUsu", column = @Column(name = "pc_fr_usu", precision = 53, scale = 0)),
			@AttributeOverride(name = "tpEmbal", column = @Column(name = "tp_embal", length = 3)),
			@AttributeOverride(name = "tpFracao", column = @Column(name = "tp_fracao", length = 4)),
			@AttributeOverride(name = "qtdeEmbal", column = @Column(name = "qtde_embal", precision = 53, scale = 0)),
			@AttributeOverride(name = "qtdeFrac", column = @Column(name = "qtde_frac", precision = 53, scale = 0)),
			@AttributeOverride(name = "percLucr", column = @Column(name = "perc_lucr", precision = 53, scale = 0)),
			@AttributeOverride(name = "tipAlt", column = @Column(name = "tip_alt", length = 1)),
			@AttributeOverride(name = "fabrica", column = @Column(name = "fabrica", length = 20)),
			@AttributeOverride(name = "cdSimpro", column = @Column(name = "cd_simpro", length = 10)),
			@AttributeOverride(name = "cdMerc", column = @Column(name = "cd_merc", length = 2)),
			@AttributeOverride(name = "percDesc", column = @Column(name = "perc_desc", precision = 53, scale = 0)),
			@AttributeOverride(name = "vlrIpi", column = @Column(name = "vlr_ipi", precision = 53, scale = 0)),
			@AttributeOverride(name = "cdRegAnv", column = @Column(name = "cd_reg_anv", length = 18)),
			@AttributeOverride(name = "dtRegAnv", column = @Column(name = "dt_reg_anv", length = 13)),
			@AttributeOverride(name = "cdBarra", column = @Column(name = "cd_barra", precision = 53, scale = 0)),
			@AttributeOverride(name = "lista", column = @Column(name = "lista", length = 1)),
			@AttributeOverride(name = "hospitalar", column = @Column(name = "hospitalar", length = 1)),
			@AttributeOverride(name = "itemFracionado", column = @Column(name = "item fracionado", length = 1)),
			@AttributeOverride(name = "cdTuss", column = @Column(name = "cd_tuss", length = 8)),
			@AttributeOverride(name = "cdClassif", column = @Column(name = "cd_classif", length = 2)),
			@AttributeOverride(name = "versao", column = @Column(name = "versao", length = 4)),
			@AttributeOverride(name = "dtVigencia", column = @Column(name = "dt_vigencia", length = 23)),
			@AttributeOverride(name = "refProduto", column = @Column(name = "ref_produto", length = 100)),
			@AttributeOverride(name = "generico", column = @Column(name = "generico", length = 1)),
			@AttributeOverride(name = "diversos", column = @Column(name = "diversos", length = 1)),
			@AttributeOverride(name = "timestamp", column = @Column(name = "timestamp", length = 23)) })
	public CgSimproInicialId getId() {
		return this.id;
	}

	public void setId(CgSimproInicialId id) {
		this.id = id;
	}

}
