package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CgSimproInicialId generated by hbm2java
 */
@Embeddable
public class CgSimproInicialId implements java.io.Serializable {

	private String cdUsuario;
	private String cdFracao;
	private String descricao;
	private Date vigencia;
	private Character identif;
	private Double pcEmFab;
	private Double pcEmVen;
	private Double pcEmUsu;
	private Double pcFrFab;
	private Double pcFrVen;
	private Double pcFrUsu;
	private String tpEmbal;
	private String tpFracao;
	private Double qtdeEmbal;
	private Double qtdeFrac;
	private Double percLucr;
	private Character tipAlt;
	private String fabrica;
	private String cdSimpro;
	private String cdMerc;
	private Double percDesc;
	private Double vlrIpi;
	private String cdRegAnv;
	private String dtRegAnv;
	private Double cdBarra;
	private Character lista;
	private Character hospitalar;
	private Character itemFracionado;
	private String cdTuss;
	private String cdClassif;
	private String versao;
	private Date dtVigencia;
	private String refProduto;
	private Character generico;
	private Character diversos;
	private Date timestamp;

	public CgSimproInicialId() {
	}

	public CgSimproInicialId(String cdUsuario, String cdFracao, String descricao, Date vigencia, Character identif,
			Double pcEmFab, Double pcEmVen, Double pcEmUsu, Double pcFrFab, Double pcFrVen, Double pcFrUsu,
			String tpEmbal, String tpFracao, Double qtdeEmbal, Double qtdeFrac, Double percLucr, Character tipAlt,
			String fabrica, String cdSimpro, String cdMerc, Double percDesc, Double vlrIpi, String cdRegAnv,
			String dtRegAnv, Double cdBarra, Character lista, Character hospitalar, Character itemFracionado,
			String cdTuss, String cdClassif, String versao, Date dtVigencia, String refProduto, Character generico,
			Character diversos, Date timestamp) {
		this.cdUsuario = cdUsuario;
		this.cdFracao = cdFracao;
		this.descricao = descricao;
		this.vigencia = vigencia;
		this.identif = identif;
		this.pcEmFab = pcEmFab;
		this.pcEmVen = pcEmVen;
		this.pcEmUsu = pcEmUsu;
		this.pcFrFab = pcFrFab;
		this.pcFrVen = pcFrVen;
		this.pcFrUsu = pcFrUsu;
		this.tpEmbal = tpEmbal;
		this.tpFracao = tpFracao;
		this.qtdeEmbal = qtdeEmbal;
		this.qtdeFrac = qtdeFrac;
		this.percLucr = percLucr;
		this.tipAlt = tipAlt;
		this.fabrica = fabrica;
		this.cdSimpro = cdSimpro;
		this.cdMerc = cdMerc;
		this.percDesc = percDesc;
		this.vlrIpi = vlrIpi;
		this.cdRegAnv = cdRegAnv;
		this.dtRegAnv = dtRegAnv;
		this.cdBarra = cdBarra;
		this.lista = lista;
		this.hospitalar = hospitalar;
		this.itemFracionado = itemFracionado;
		this.cdTuss = cdTuss;
		this.cdClassif = cdClassif;
		this.versao = versao;
		this.dtVigencia = dtVigencia;
		this.refProduto = refProduto;
		this.generico = generico;
		this.diversos = diversos;
		this.timestamp = timestamp;
	}

	@Column(name = "cd_usuario", length = 15)
	public String getCdUsuario() {
		return this.cdUsuario;
	}

	public void setCdUsuario(String cdUsuario) {
		this.cdUsuario = cdUsuario;
	}

	@Column(name = "cd_fracao", length = 15)
	public String getCdFracao() {
		return this.cdFracao;
	}

	public void setCdFracao(String cdFracao) {
		this.cdFracao = cdFracao;
	}

	@Column(name = "descricao", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "vigencia", length = 10)
	public Date getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(Date vigencia) {
		this.vigencia = vigencia;
	}

	@Column(name = "identif", length = 1)
	public Character getIdentif() {
		return this.identif;
	}

	public void setIdentif(Character identif) {
		this.identif = identif;
	}

	@Column(name = "pc_em_fab", precision = 53, scale = 0)
	public Double getPcEmFab() {
		return this.pcEmFab;
	}

	public void setPcEmFab(Double pcEmFab) {
		this.pcEmFab = pcEmFab;
	}

	@Column(name = "pc_em_ven", precision = 53, scale = 0)
	public Double getPcEmVen() {
		return this.pcEmVen;
	}

	public void setPcEmVen(Double pcEmVen) {
		this.pcEmVen = pcEmVen;
	}

	@Column(name = "pc_em_usu", precision = 53, scale = 0)
	public Double getPcEmUsu() {
		return this.pcEmUsu;
	}

	public void setPcEmUsu(Double pcEmUsu) {
		this.pcEmUsu = pcEmUsu;
	}

	@Column(name = "pc_fr_fab", precision = 53, scale = 0)
	public Double getPcFrFab() {
		return this.pcFrFab;
	}

	public void setPcFrFab(Double pcFrFab) {
		this.pcFrFab = pcFrFab;
	}

	@Column(name = "pc_fr_ven", precision = 53, scale = 0)
	public Double getPcFrVen() {
		return this.pcFrVen;
	}

	public void setPcFrVen(Double pcFrVen) {
		this.pcFrVen = pcFrVen;
	}

	@Column(name = "pc_fr_usu", precision = 53, scale = 0)
	public Double getPcFrUsu() {
		return this.pcFrUsu;
	}

	public void setPcFrUsu(Double pcFrUsu) {
		this.pcFrUsu = pcFrUsu;
	}

	@Column(name = "tp_embal", length = 3)
	public String getTpEmbal() {
		return this.tpEmbal;
	}

	public void setTpEmbal(String tpEmbal) {
		this.tpEmbal = tpEmbal;
	}

	@Column(name = "tp_fracao", length = 4)
	public String getTpFracao() {
		return this.tpFracao;
	}

	public void setTpFracao(String tpFracao) {
		this.tpFracao = tpFracao;
	}

	@Column(name = "qtde_embal", precision = 53, scale = 0)
	public Double getQtdeEmbal() {
		return this.qtdeEmbal;
	}

	public void setQtdeEmbal(Double qtdeEmbal) {
		this.qtdeEmbal = qtdeEmbal;
	}

	@Column(name = "qtde_frac", precision = 53, scale = 0)
	public Double getQtdeFrac() {
		return this.qtdeFrac;
	}

	public void setQtdeFrac(Double qtdeFrac) {
		this.qtdeFrac = qtdeFrac;
	}

	@Column(name = "perc_lucr", precision = 53, scale = 0)
	public Double getPercLucr() {
		return this.percLucr;
	}

	public void setPercLucr(Double percLucr) {
		this.percLucr = percLucr;
	}

	@Column(name = "tip_alt", length = 1)
	public Character getTipAlt() {
		return this.tipAlt;
	}

	public void setTipAlt(Character tipAlt) {
		this.tipAlt = tipAlt;
	}

	@Column(name = "fabrica", length = 20)
	public String getFabrica() {
		return this.fabrica;
	}

	public void setFabrica(String fabrica) {
		this.fabrica = fabrica;
	}

	@Column(name = "cd_simpro", length = 10)
	public String getCdSimpro() {
		return this.cdSimpro;
	}

	public void setCdSimpro(String cdSimpro) {
		this.cdSimpro = cdSimpro;
	}

	@Column(name = "cd_merc", length = 2)
	public String getCdMerc() {
		return this.cdMerc;
	}

	public void setCdMerc(String cdMerc) {
		this.cdMerc = cdMerc;
	}

	@Column(name = "perc_desc", precision = 53, scale = 0)
	public Double getPercDesc() {
		return this.percDesc;
	}

	public void setPercDesc(Double percDesc) {
		this.percDesc = percDesc;
	}

	@Column(name = "vlr_ipi", precision = 53, scale = 0)
	public Double getVlrIpi() {
		return this.vlrIpi;
	}

	public void setVlrIpi(Double vlrIpi) {
		this.vlrIpi = vlrIpi;
	}

	@Column(name = "cd_reg_anv", length = 18)
	public String getCdRegAnv() {
		return this.cdRegAnv;
	}

	public void setCdRegAnv(String cdRegAnv) {
		this.cdRegAnv = cdRegAnv;
	}

	@Column(name = "dt_reg_anv", length = 13)
	public String getDtRegAnv() {
		return this.dtRegAnv;
	}

	public void setDtRegAnv(String dtRegAnv) {
		this.dtRegAnv = dtRegAnv;
	}

	@Column(name = "cd_barra", precision = 53, scale = 0)
	public Double getCdBarra() {
		return this.cdBarra;
	}

	public void setCdBarra(Double cdBarra) {
		this.cdBarra = cdBarra;
	}

	@Column(name = "lista", length = 1)
	public Character getLista() {
		return this.lista;
	}

	public void setLista(Character lista) {
		this.lista = lista;
	}

	@Column(name = "hospitalar", length = 1)
	public Character getHospitalar() {
		return this.hospitalar;
	}

	public void setHospitalar(Character hospitalar) {
		this.hospitalar = hospitalar;
	}

	@Column(name = "item fracionado", length = 1)
	public Character getItemFracionado() {
		return this.itemFracionado;
	}

	public void setItemFracionado(Character itemFracionado) {
		this.itemFracionado = itemFracionado;
	}

	@Column(name = "cd_tuss", length = 8)
	public String getCdTuss() {
		return this.cdTuss;
	}

	public void setCdTuss(String cdTuss) {
		this.cdTuss = cdTuss;
	}

	@Column(name = "cd_classif", length = 2)
	public String getCdClassif() {
		return this.cdClassif;
	}

	public void setCdClassif(String cdClassif) {
		this.cdClassif = cdClassif;
	}

	@Column(name = "versao", length = 4)
	public String getVersao() {
		return this.versao;
	}

	public void setVersao(String versao) {
		this.versao = versao;
	}

	@Column(name = "dt_vigencia", length = 23)
	public Date getDtVigencia() {
		return this.dtVigencia;
	}

	public void setDtVigencia(Date dtVigencia) {
		this.dtVigencia = dtVigencia;
	}

	@Column(name = "ref_produto", length = 100)
	public String getRefProduto() {
		return this.refProduto;
	}

	public void setRefProduto(String refProduto) {
		this.refProduto = refProduto;
	}

	@Column(name = "generico", length = 1)
	public Character getGenerico() {
		return this.generico;
	}

	public void setGenerico(Character generico) {
		this.generico = generico;
	}

	@Column(name = "diversos", length = 1)
	public Character getDiversos() {
		return this.diversos;
	}

	public void setDiversos(Character diversos) {
		this.diversos = diversos;
	}

	@Column(name = "timestamp", length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CgSimproInicialId))
			return false;
		CgSimproInicialId castOther = (CgSimproInicialId) other;

		return ((this.getCdUsuario() == castOther.getCdUsuario()) || (this.getCdUsuario() != null
				&& castOther.getCdUsuario() != null && this.getCdUsuario().equals(castOther.getCdUsuario())))
				&& ((this.getCdFracao() == castOther.getCdFracao()) || (this.getCdFracao() != null
						&& castOther.getCdFracao() != null && this.getCdFracao().equals(castOther.getCdFracao())))
				&& ((this.getDescricao() == castOther.getDescricao()) || (this.getDescricao() != null
						&& castOther.getDescricao() != null && this.getDescricao().equals(castOther.getDescricao())))
				&& ((this.getVigencia() == castOther.getVigencia()) || (this.getVigencia() != null
						&& castOther.getVigencia() != null && this.getVigencia().equals(castOther.getVigencia())))
				&& ((this.getIdentif() == castOther.getIdentif()) || (this.getIdentif() != null
						&& castOther.getIdentif() != null && this.getIdentif().equals(castOther.getIdentif())))
				&& ((this.getPcEmFab() == castOther.getPcEmFab()) || (this.getPcEmFab() != null
						&& castOther.getPcEmFab() != null && this.getPcEmFab().equals(castOther.getPcEmFab())))
				&& ((this.getPcEmVen() == castOther.getPcEmVen()) || (this.getPcEmVen() != null
						&& castOther.getPcEmVen() != null && this.getPcEmVen().equals(castOther.getPcEmVen())))
				&& ((this.getPcEmUsu() == castOther.getPcEmUsu()) || (this.getPcEmUsu() != null
						&& castOther.getPcEmUsu() != null && this.getPcEmUsu().equals(castOther.getPcEmUsu())))
				&& ((this.getPcFrFab() == castOther.getPcFrFab()) || (this.getPcFrFab() != null
						&& castOther.getPcFrFab() != null && this.getPcFrFab().equals(castOther.getPcFrFab())))
				&& ((this.getPcFrVen() == castOther.getPcFrVen()) || (this.getPcFrVen() != null
						&& castOther.getPcFrVen() != null && this.getPcFrVen().equals(castOther.getPcFrVen())))
				&& ((this.getPcFrUsu() == castOther.getPcFrUsu()) || (this.getPcFrUsu() != null
						&& castOther.getPcFrUsu() != null && this.getPcFrUsu().equals(castOther.getPcFrUsu())))
				&& ((this.getTpEmbal() == castOther.getTpEmbal()) || (this.getTpEmbal() != null
						&& castOther.getTpEmbal() != null && this.getTpEmbal().equals(castOther.getTpEmbal())))
				&& ((this.getTpFracao() == castOther.getTpFracao()) || (this.getTpFracao() != null
						&& castOther.getTpFracao() != null && this.getTpFracao().equals(castOther.getTpFracao())))
				&& ((this.getQtdeEmbal() == castOther.getQtdeEmbal()) || (this.getQtdeEmbal() != null
						&& castOther.getQtdeEmbal() != null && this.getQtdeEmbal().equals(castOther.getQtdeEmbal())))
				&& ((this.getQtdeFrac() == castOther.getQtdeFrac()) || (this.getQtdeFrac() != null
						&& castOther.getQtdeFrac() != null && this.getQtdeFrac().equals(castOther.getQtdeFrac())))
				&& ((this.getPercLucr() == castOther.getPercLucr()) || (this.getPercLucr() != null
						&& castOther.getPercLucr() != null && this.getPercLucr().equals(castOther.getPercLucr())))
				&& ((this.getTipAlt() == castOther.getTipAlt()) || (this.getTipAlt() != null
						&& castOther.getTipAlt() != null && this.getTipAlt().equals(castOther.getTipAlt())))
				&& ((this.getFabrica() == castOther.getFabrica()) || (this.getFabrica() != null
						&& castOther.getFabrica() != null && this.getFabrica().equals(castOther.getFabrica())))
				&& ((this.getCdSimpro() == castOther.getCdSimpro()) || (this.getCdSimpro() != null
						&& castOther.getCdSimpro() != null && this.getCdSimpro().equals(castOther.getCdSimpro())))
				&& ((this.getCdMerc() == castOther.getCdMerc()) || (this.getCdMerc() != null
						&& castOther.getCdMerc() != null && this.getCdMerc().equals(castOther.getCdMerc())))
				&& ((this.getPercDesc() == castOther.getPercDesc()) || (this.getPercDesc() != null
						&& castOther.getPercDesc() != null && this.getPercDesc().equals(castOther.getPercDesc())))
				&& ((this.getVlrIpi() == castOther.getVlrIpi()) || (this.getVlrIpi() != null
						&& castOther.getVlrIpi() != null && this.getVlrIpi().equals(castOther.getVlrIpi())))
				&& ((this.getCdRegAnv() == castOther.getCdRegAnv()) || (this.getCdRegAnv() != null
						&& castOther.getCdRegAnv() != null && this.getCdRegAnv().equals(castOther.getCdRegAnv())))
				&& ((this.getDtRegAnv() == castOther.getDtRegAnv()) || (this.getDtRegAnv() != null
						&& castOther.getDtRegAnv() != null && this.getDtRegAnv().equals(castOther.getDtRegAnv())))
				&& ((this.getCdBarra() == castOther.getCdBarra()) || (this.getCdBarra() != null
						&& castOther.getCdBarra() != null && this.getCdBarra().equals(castOther.getCdBarra())))
				&& ((this.getLista() == castOther.getLista()) || (this.getLista() != null
						&& castOther.getLista() != null && this.getLista().equals(castOther.getLista())))
				&& ((this.getHospitalar() == castOther.getHospitalar()) || (this.getHospitalar() != null
						&& castOther.getHospitalar() != null && this.getHospitalar().equals(castOther.getHospitalar())))
				&& ((this.getItemFracionado() == castOther.getItemFracionado())
						|| (this.getItemFracionado() != null && castOther.getItemFracionado() != null
								&& this.getItemFracionado().equals(castOther.getItemFracionado())))
				&& ((this.getCdTuss() == castOther.getCdTuss()) || (this.getCdTuss() != null
						&& castOther.getCdTuss() != null && this.getCdTuss().equals(castOther.getCdTuss())))
				&& ((this.getCdClassif() == castOther.getCdClassif()) || (this.getCdClassif() != null
						&& castOther.getCdClassif() != null && this.getCdClassif().equals(castOther.getCdClassif())))
				&& ((this.getVersao() == castOther.getVersao()) || (this.getVersao() != null
						&& castOther.getVersao() != null && this.getVersao().equals(castOther.getVersao())))
				&& ((this.getDtVigencia() == castOther.getDtVigencia()) || (this.getDtVigencia() != null
						&& castOther.getDtVigencia() != null && this.getDtVigencia().equals(castOther.getDtVigencia())))
				&& ((this.getRefProduto() == castOther.getRefProduto()) || (this.getRefProduto() != null
						&& castOther.getRefProduto() != null && this.getRefProduto().equals(castOther.getRefProduto())))
				&& ((this.getGenerico() == castOther.getGenerico()) || (this.getGenerico() != null
						&& castOther.getGenerico() != null && this.getGenerico().equals(castOther.getGenerico())))
				&& ((this.getDiversos() == castOther.getDiversos()) || (this.getDiversos() != null
						&& castOther.getDiversos() != null && this.getDiversos().equals(castOther.getDiversos())))
				&& ((this.getTimestamp() == castOther.getTimestamp()) || (this.getTimestamp() != null
						&& castOther.getTimestamp() != null && this.getTimestamp().equals(castOther.getTimestamp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCdUsuario() == null ? 0 : this.getCdUsuario().hashCode());
		result = 37 * result + (getCdFracao() == null ? 0 : this.getCdFracao().hashCode());
		result = 37 * result + (getDescricao() == null ? 0 : this.getDescricao().hashCode());
		result = 37 * result + (getVigencia() == null ? 0 : this.getVigencia().hashCode());
		result = 37 * result + (getIdentif() == null ? 0 : this.getIdentif().hashCode());
		result = 37 * result + (getPcEmFab() == null ? 0 : this.getPcEmFab().hashCode());
		result = 37 * result + (getPcEmVen() == null ? 0 : this.getPcEmVen().hashCode());
		result = 37 * result + (getPcEmUsu() == null ? 0 : this.getPcEmUsu().hashCode());
		result = 37 * result + (getPcFrFab() == null ? 0 : this.getPcFrFab().hashCode());
		result = 37 * result + (getPcFrVen() == null ? 0 : this.getPcFrVen().hashCode());
		result = 37 * result + (getPcFrUsu() == null ? 0 : this.getPcFrUsu().hashCode());
		result = 37 * result + (getTpEmbal() == null ? 0 : this.getTpEmbal().hashCode());
		result = 37 * result + (getTpFracao() == null ? 0 : this.getTpFracao().hashCode());
		result = 37 * result + (getQtdeEmbal() == null ? 0 : this.getQtdeEmbal().hashCode());
		result = 37 * result + (getQtdeFrac() == null ? 0 : this.getQtdeFrac().hashCode());
		result = 37 * result + (getPercLucr() == null ? 0 : this.getPercLucr().hashCode());
		result = 37 * result + (getTipAlt() == null ? 0 : this.getTipAlt().hashCode());
		result = 37 * result + (getFabrica() == null ? 0 : this.getFabrica().hashCode());
		result = 37 * result + (getCdSimpro() == null ? 0 : this.getCdSimpro().hashCode());
		result = 37 * result + (getCdMerc() == null ? 0 : this.getCdMerc().hashCode());
		result = 37 * result + (getPercDesc() == null ? 0 : this.getPercDesc().hashCode());
		result = 37 * result + (getVlrIpi() == null ? 0 : this.getVlrIpi().hashCode());
		result = 37 * result + (getCdRegAnv() == null ? 0 : this.getCdRegAnv().hashCode());
		result = 37 * result + (getDtRegAnv() == null ? 0 : this.getDtRegAnv().hashCode());
		result = 37 * result + (getCdBarra() == null ? 0 : this.getCdBarra().hashCode());
		result = 37 * result + (getLista() == null ? 0 : this.getLista().hashCode());
		result = 37 * result + (getHospitalar() == null ? 0 : this.getHospitalar().hashCode());
		result = 37 * result + (getItemFracionado() == null ? 0 : this.getItemFracionado().hashCode());
		result = 37 * result + (getCdTuss() == null ? 0 : this.getCdTuss().hashCode());
		result = 37 * result + (getCdClassif() == null ? 0 : this.getCdClassif().hashCode());
		result = 37 * result + (getVersao() == null ? 0 : this.getVersao().hashCode());
		result = 37 * result + (getDtVigencia() == null ? 0 : this.getDtVigencia().hashCode());
		result = 37 * result + (getRefProduto() == null ? 0 : this.getRefProduto().hashCode());
		result = 37 * result + (getGenerico() == null ? 0 : this.getGenerico().hashCode());
		result = 37 * result + (getDiversos() == null ? 0 : this.getDiversos().hashCode());
		result = 37 * result + (getTimestamp() == null ? 0 : this.getTimestamp().hashCode());
		return result;
	}

}
