package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmissaoCarteira generated by hbm2java
 */
@Entity
@Table(name = "EMISSAO_CARTEIRA")
public class EmissaoCarteira implements java.io.Serializable {

	private EmissaoCarteiraId id;
	private Date dthrEmissao;
	private Date dtValidade;
	private short idUsuario;
	private Date timestamp;
	private Integer seq;
	private CancelamentoCarteira cancelamentoCarteira;

	public EmissaoCarteira() {
	}

	public EmissaoCarteira(EmissaoCarteiraId id, Date dthrEmissao, Date dtValidade, short idUsuario, Date timestamp) {
		this.id = id;
		this.dthrEmissao = dthrEmissao;
		this.dtValidade = dtValidade;
		this.idUsuario = idUsuario;
		this.timestamp = timestamp;
	}

	public EmissaoCarteira(EmissaoCarteiraId id, Date dthrEmissao, Date dtValidade, short idUsuario, Date timestamp,
			Integer seq, CancelamentoCarteira cancelamentoCarteira) {
		this.id = id;
		this.dthrEmissao = dthrEmissao;
		this.dtValidade = dtValidade;
		this.idUsuario = idUsuario;
		this.timestamp = timestamp;
		this.seq = seq;
		this.cancelamentoCarteira = cancelamentoCarteira;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "numeroCarteira", column = @Column(name = "numero_carteira", nullable = false, precision = 17, scale = 0)),
			@AttributeOverride(name = "dv", column = @Column(name = "dv", nullable = false)) })
	public EmissaoCarteiraId getId() {
		return this.id;
	}

	public void setId(EmissaoCarteiraId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_emissao", nullable = false, length = 23)
	public Date getDthrEmissao() {
		return this.dthrEmissao;
	}

	public void setDthrEmissao(Date dthrEmissao) {
		this.dthrEmissao = dthrEmissao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_validade", nullable = false, length = 23)
	public Date getDtValidade() {
		return this.dtValidade;
	}

	public void setDtValidade(Date dtValidade) {
		this.dtValidade = dtValidade;
	}

	@Column(name = "id_usuario", nullable = false)
	public short getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(short idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "SEQ")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "emissaoCarteira")
	public CancelamentoCarteira getCancelamentoCarteira() {
		return this.cancelamentoCarteira;
	}

	public void setCancelamentoCarteira(CancelamentoCarteira cancelamentoCarteira) {
		this.cancelamentoCarteira = cancelamentoCarteira;
	}

}
