package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GuiaOcupacional generated by hbm2java
 */
@Entity
@Table(name = "GUIA_OCUPACIONAL")
public class GuiaOcupacional implements java.io.Serializable {

	private int idGuiaOcupacional;
	private PrestadorCadastrado prestadorCadastrado;
	private long numeroCarteira;
	private int idDocumento;
	private Integer idEnderecoPrestador;
	private boolean FMotorhome;
	private boolean FNucleo;
	private boolean FSede;
	private int idComandoOcupacional;
	private char DSequencialComando;
	private Date timestamp;

	public GuiaOcupacional() {
	}

	public GuiaOcupacional(int idGuiaOcupacional, long numeroCarteira, int idDocumento, boolean FMotorhome,
			boolean FNucleo, boolean FSede, int idComandoOcupacional, char DSequencialComando, Date timestamp) {
		this.idGuiaOcupacional = idGuiaOcupacional;
		this.numeroCarteira = numeroCarteira;
		this.idDocumento = idDocumento;
		this.FMotorhome = FMotorhome;
		this.FNucleo = FNucleo;
		this.FSede = FSede;
		this.idComandoOcupacional = idComandoOcupacional;
		this.DSequencialComando = DSequencialComando;
		this.timestamp = timestamp;
	}

	public GuiaOcupacional(int idGuiaOcupacional, PrestadorCadastrado prestadorCadastrado, long numeroCarteira,
			int idDocumento, Integer idEnderecoPrestador, boolean FMotorhome, boolean FNucleo, boolean FSede,
			int idComandoOcupacional, char DSequencialComando, Date timestamp) {
		this.idGuiaOcupacional = idGuiaOcupacional;
		this.prestadorCadastrado = prestadorCadastrado;
		this.numeroCarteira = numeroCarteira;
		this.idDocumento = idDocumento;
		this.idEnderecoPrestador = idEnderecoPrestador;
		this.FMotorhome = FMotorhome;
		this.FNucleo = FNucleo;
		this.FSede = FSede;
		this.idComandoOcupacional = idComandoOcupacional;
		this.DSequencialComando = DSequencialComando;
		this.timestamp = timestamp;
	}

	@Id

	@Column(name = "id_guia_ocupacional", unique = true, nullable = false)
	public int getIdGuiaOcupacional() {
		return this.idGuiaOcupacional;
	}

	public void setIdGuiaOcupacional(int idGuiaOcupacional) {
		this.idGuiaOcupacional = idGuiaOcupacional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestador")
	public PrestadorCadastrado getPrestadorCadastrado() {
		return this.prestadorCadastrado;
	}

	public void setPrestadorCadastrado(PrestadorCadastrado prestadorCadastrado) {
		this.prestadorCadastrado = prestadorCadastrado;
	}

	@Column(name = "numero_carteira", nullable = false, precision = 17, scale = 0)
	public long getNumeroCarteira() {
		return this.numeroCarteira;
	}

	public void setNumeroCarteira(long numeroCarteira) {
		this.numeroCarteira = numeroCarteira;
	}

	@Column(name = "id_documento", nullable = false)
	public int getIdDocumento() {
		return this.idDocumento;
	}

	public void setIdDocumento(int idDocumento) {
		this.idDocumento = idDocumento;
	}

	@Column(name = "id_endereco_prestador")
	public Integer getIdEnderecoPrestador() {
		return this.idEnderecoPrestador;
	}

	public void setIdEnderecoPrestador(Integer idEnderecoPrestador) {
		this.idEnderecoPrestador = idEnderecoPrestador;
	}

	@Column(name = "f_motorhome", nullable = false)
	public boolean isFMotorhome() {
		return this.FMotorhome;
	}

	public void setFMotorhome(boolean FMotorhome) {
		this.FMotorhome = FMotorhome;
	}

	@Column(name = "f_nucleo", nullable = false)
	public boolean isFNucleo() {
		return this.FNucleo;
	}

	public void setFNucleo(boolean FNucleo) {
		this.FNucleo = FNucleo;
	}

	@Column(name = "f_sede", nullable = false)
	public boolean isFSede() {
		return this.FSede;
	}

	public void setFSede(boolean FSede) {
		this.FSede = FSede;
	}

	@Column(name = "id_comando_ocupacional", nullable = false)
	public int getIdComandoOcupacional() {
		return this.idComandoOcupacional;
	}

	public void setIdComandoOcupacional(int idComandoOcupacional) {
		this.idComandoOcupacional = idComandoOcupacional;
	}

	@Column(name = "d_sequencial_comando", nullable = false, length = 1)
	public char getDSequencialComando() {
		return this.DSequencialComando;
	}

	public void setDSequencialComando(char DSequencialComando) {
		this.DSequencialComando = DSequencialComando;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

}
