package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GuiaId generated by hbm2java
 */
@Embeddable
public class GuiaId implements java.io.Serializable {

	private int idGuia;
	private int idTipoGuia;

	public GuiaId() {
	}

	public GuiaId(int idGuia, int idTipoGuia) {
		this.idGuia = idGuia;
		this.idTipoGuia = idTipoGuia;
	}

	@Column(name = "id_guia", nullable = false)
	public int getIdGuia() {
		return this.idGuia;
	}

	public void setIdGuia(int idGuia) {
		this.idGuia = idGuia;
	}

	@Column(name = "id_tipo_guia", nullable = false)
	public int getIdTipoGuia() {
		return this.idTipoGuia;
	}

	public void setIdTipoGuia(int idTipoGuia) {
		this.idTipoGuia = idTipoGuia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GuiaId))
			return false;
		GuiaId castOther = (GuiaId) other;

		return (this.getIdGuia() == castOther.getIdGuia()) && (this.getIdTipoGuia() == castOther.getIdTipoGuia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGuia();
		result = 37 * result + this.getIdTipoGuia();
		return result;
	}

}
