package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Guia generated by hbm2java
 */
@Entity
@Table(name = "GUIA", schema = "dbo", catalog = "CacDb", uniqueConstraints = @UniqueConstraint(columnNames = "id_solicitacao"))
public class Guia implements java.io.Serializable {

	private GuiaId id;
	private Guia guia;
	private TipoGuia tipoGuia;
	private Date dthrEmissao;
	private Date dtValidade;
	private Integer idEvento;
	private int idSolicitacao;
	private String idCidPrincipal;
	private Integer idEspecialidade;
	private String diagnostico;
	private Date dtInternacao;
	private String hrInternacao;
	private Date dtAlta;
	private String hrAlta;
	private Integer diasAutorizados;
	private Date dthrCancelamento;
	private Integer idMotivoCancelamentoGuia;
	private int idPessoa;
	private int idPlano;
	private int idSubPlano;
	private Date dtInscricao;
	private Short diasCancelados;
	private boolean FGuiaHomologada;
	private Byte idParticipacaoTratSeriado;
	private Date timestamp;
	private Character DTipoAlta;
	private Byte FVisitaProgramada;
	private Date dthrLiberacaoGuia;
	private Character DStatusDesbloqueio;
	private Integer senhaDesbloqueio;
	private Integer idMotivoEncerramento;
	private Set<Guia> guias = new HashSet<Guia>(0);

	public Guia() {
	}

	public Guia(GuiaId id, TipoGuia tipoGuia, Date dthrEmissao, Date dtValidade, int idSolicitacao, int idPessoa,
			int idPlano, int idSubPlano, Date dtInscricao, boolean FGuiaHomologada, Date timestamp) {
		this.id = id;
		this.tipoGuia = tipoGuia;
		this.dthrEmissao = dthrEmissao;
		this.dtValidade = dtValidade;
		this.idSolicitacao = idSolicitacao;
		this.idPessoa = idPessoa;
		this.idPlano = idPlano;
		this.idSubPlano = idSubPlano;
		this.dtInscricao = dtInscricao;
		this.FGuiaHomologada = FGuiaHomologada;
		this.timestamp = timestamp;
	}

	public Guia(GuiaId id, Guia guia, TipoGuia tipoGuia, Date dthrEmissao, Date dtValidade, Integer idEvento,
			int idSolicitacao, String idCidPrincipal, Integer idEspecialidade, String diagnostico, Date dtInternacao,
			String hrInternacao, Date dtAlta, String hrAlta, Integer diasAutorizados, Date dthrCancelamento,
			Integer idMotivoCancelamentoGuia, int idPessoa, int idPlano, int idSubPlano, Date dtInscricao,
			Short diasCancelados, boolean FGuiaHomologada, Byte idParticipacaoTratSeriado, Date timestamp,
			Character DTipoAlta, Byte FVisitaProgramada, Date dthrLiberacaoGuia, Character DStatusDesbloqueio,
			Integer senhaDesbloqueio, Integer idMotivoEncerramento, Set<Guia> guias) {
		this.id = id;
		this.guia = guia;
		this.tipoGuia = tipoGuia;
		this.dthrEmissao = dthrEmissao;
		this.dtValidade = dtValidade;
		this.idEvento = idEvento;
		this.idSolicitacao = idSolicitacao;
		this.idCidPrincipal = idCidPrincipal;
		this.idEspecialidade = idEspecialidade;
		this.diagnostico = diagnostico;
		this.dtInternacao = dtInternacao;
		this.hrInternacao = hrInternacao;
		this.dtAlta = dtAlta;
		this.hrAlta = hrAlta;
		this.diasAutorizados = diasAutorizados;
		this.dthrCancelamento = dthrCancelamento;
		this.idMotivoCancelamentoGuia = idMotivoCancelamentoGuia;
		this.idPessoa = idPessoa;
		this.idPlano = idPlano;
		this.idSubPlano = idSubPlano;
		this.dtInscricao = dtInscricao;
		this.diasCancelados = diasCancelados;
		this.FGuiaHomologada = FGuiaHomologada;
		this.idParticipacaoTratSeriado = idParticipacaoTratSeriado;
		this.timestamp = timestamp;
		this.DTipoAlta = DTipoAlta;
		this.FVisitaProgramada = FVisitaProgramada;
		this.dthrLiberacaoGuia = dthrLiberacaoGuia;
		this.DStatusDesbloqueio = DStatusDesbloqueio;
		this.senhaDesbloqueio = senhaDesbloqueio;
		this.idMotivoEncerramento = idMotivoEncerramento;
		this.guias = guias;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idGuia", column = @Column(name = "id_guia", nullable = false)),
			@AttributeOverride(name = "idTipoGuia", column = @Column(name = "id_tipo_guia", nullable = false)) })
	public GuiaId getId() {
		return this.id;
	}

	public void setId(GuiaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "id_guia_associada", referencedColumnName = "id_guia"),
			@JoinColumn(name = "id_tipo_guia_associada", referencedColumnName = "id_tipo_guia") })
	public Guia getGuia() {
		return this.guia;
	}

	public void setGuia(Guia guia) {
		this.guia = guia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_guia", nullable = false, insertable = false, updatable = false)
	public TipoGuia getTipoGuia() {
		return this.tipoGuia;
	}

	public void setTipoGuia(TipoGuia tipoGuia) {
		this.tipoGuia = tipoGuia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_emissao", nullable = false, length = 23)
	public Date getDthrEmissao() {
		return this.dthrEmissao;
	}

	public void setDthrEmissao(Date dthrEmissao) {
		this.dthrEmissao = dthrEmissao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_validade", nullable = false, length = 23)
	public Date getDtValidade() {
		return this.dtValidade;
	}

	public void setDtValidade(Date dtValidade) {
		this.dtValidade = dtValidade;
	}

	@Column(name = "id_evento")
	public Integer getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	@Column(name = "id_solicitacao", unique = true, nullable = false)
	public int getIdSolicitacao() {
		return this.idSolicitacao;
	}

	public void setIdSolicitacao(int idSolicitacao) {
		this.idSolicitacao = idSolicitacao;
	}

	@Column(name = "id_cid_principal", length = 5)
	public String getIdCidPrincipal() {
		return this.idCidPrincipal;
	}

	public void setIdCidPrincipal(String idCidPrincipal) {
		this.idCidPrincipal = idCidPrincipal;
	}

	@Column(name = "id_especialidade")
	public Integer getIdEspecialidade() {
		return this.idEspecialidade;
	}

	public void setIdEspecialidade(Integer idEspecialidade) {
		this.idEspecialidade = idEspecialidade;
	}

	@Column(name = "diagnostico", length = 50)
	public String getDiagnostico() {
		return this.diagnostico;
	}

	public void setDiagnostico(String diagnostico) {
		this.diagnostico = diagnostico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_internacao", length = 23)
	public Date getDtInternacao() {
		return this.dtInternacao;
	}

	public void setDtInternacao(Date dtInternacao) {
		this.dtInternacao = dtInternacao;
	}

	@Column(name = "hr_internacao", length = 5)
	public String getHrInternacao() {
		return this.hrInternacao;
	}

	public void setHrInternacao(String hrInternacao) {
		this.hrInternacao = hrInternacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_alta", length = 23)
	public Date getDtAlta() {
		return this.dtAlta;
	}

	public void setDtAlta(Date dtAlta) {
		this.dtAlta = dtAlta;
	}

	@Column(name = "hr_alta", length = 5)
	public String getHrAlta() {
		return this.hrAlta;
	}

	public void setHrAlta(String hrAlta) {
		this.hrAlta = hrAlta;
	}

	@Column(name = "dias_autorizados")
	public Integer getDiasAutorizados() {
		return this.diasAutorizados;
	}

	public void setDiasAutorizados(Integer diasAutorizados) {
		this.diasAutorizados = diasAutorizados;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_cancelamento", length = 23)
	public Date getDthrCancelamento() {
		return this.dthrCancelamento;
	}

	public void setDthrCancelamento(Date dthrCancelamento) {
		this.dthrCancelamento = dthrCancelamento;
	}

	@Column(name = "id_motivo_cancelamento_guia")
	public Integer getIdMotivoCancelamentoGuia() {
		return this.idMotivoCancelamentoGuia;
	}

	public void setIdMotivoCancelamentoGuia(Integer idMotivoCancelamentoGuia) {
		this.idMotivoCancelamentoGuia = idMotivoCancelamentoGuia;
	}

	@Column(name = "id_pessoa", nullable = false)
	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	@Column(name = "id_plano", nullable = false)
	public int getIdPlano() {
		return this.idPlano;
	}

	public void setIdPlano(int idPlano) {
		this.idPlano = idPlano;
	}

	@Column(name = "id_sub_plano", nullable = false)
	public int getIdSubPlano() {
		return this.idSubPlano;
	}

	public void setIdSubPlano(int idSubPlano) {
		this.idSubPlano = idSubPlano;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inscricao", nullable = false, length = 23)
	public Date getDtInscricao() {
		return this.dtInscricao;
	}

	public void setDtInscricao(Date dtInscricao) {
		this.dtInscricao = dtInscricao;
	}

	@Column(name = "dias_cancelados")
	public Short getDiasCancelados() {
		return this.diasCancelados;
	}

	public void setDiasCancelados(Short diasCancelados) {
		this.diasCancelados = diasCancelados;
	}

	@Column(name = "f_guia_homologada", nullable = false)
	public boolean isFGuiaHomologada() {
		return this.FGuiaHomologada;
	}

	public void setFGuiaHomologada(boolean FGuiaHomologada) {
		this.FGuiaHomologada = FGuiaHomologada;
	}

	@Column(name = "id_participacao_trat_seriado")
	public Byte getIdParticipacaoTratSeriado() {
		return this.idParticipacaoTratSeriado;
	}

	public void setIdParticipacaoTratSeriado(Byte idParticipacaoTratSeriado) {
		this.idParticipacaoTratSeriado = idParticipacaoTratSeriado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "d_tipo_alta", length = 1)
	public Character getDTipoAlta() {
		return this.DTipoAlta;
	}

	public void setDTipoAlta(Character DTipoAlta) {
		this.DTipoAlta = DTipoAlta;
	}

	@Column(name = "f_visita_programada")
	public Byte getFVisitaProgramada() {
		return this.FVisitaProgramada;
	}

	public void setFVisitaProgramada(Byte FVisitaProgramada) {
		this.FVisitaProgramada = FVisitaProgramada;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_liberacao_guia", length = 23)
	public Date getDthrLiberacaoGuia() {
		return this.dthrLiberacaoGuia;
	}

	public void setDthrLiberacaoGuia(Date dthrLiberacaoGuia) {
		this.dthrLiberacaoGuia = dthrLiberacaoGuia;
	}

	@Column(name = "d_status_desbloqueio", length = 1)
	public Character getDStatusDesbloqueio() {
		return this.DStatusDesbloqueio;
	}

	public void setDStatusDesbloqueio(Character DStatusDesbloqueio) {
		this.DStatusDesbloqueio = DStatusDesbloqueio;
	}

	@Column(name = "senha_desbloqueio")
	public Integer getSenhaDesbloqueio() {
		return this.senhaDesbloqueio;
	}

	public void setSenhaDesbloqueio(Integer senhaDesbloqueio) {
		this.senhaDesbloqueio = senhaDesbloqueio;
	}

	@Column(name = "id_motivo_encerramento")
	public Integer getIdMotivoEncerramento() {
		return this.idMotivoEncerramento;
	}

	public void setIdMotivoEncerramento(Integer idMotivoEncerramento) {
		this.idMotivoEncerramento = idMotivoEncerramento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "guia")
	public Set<Guia> getGuias() {
		return this.guias;
	}

	public void setGuias(Set<Guia> guias) {
		this.guias = guias;
	}

}
