package br.com.pojos.suporte;
// Generated 09/06/2016 19:01:50 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prestador generated by hbm2java
 */
@Entity
@Table(name = "PRESTADOR")
public class Prestador implements java.io.Serializable {

	private int idPrestador;
	private Prestador prestador;
	private char DTipoPessoa;
	private String cpfCgc;
	private String nome;
	private Date dtCadastramento;
	private String inss;
	private String EMail;
	private char DTipoPrestador;
	private boolean FIsentoIss;
	private boolean FPagamentoSegueCronograma;
	private boolean FEntregaNotaFiscal;
	private boolean FCooperativa;
	private Date timestamp;
	private Integer codPres;
	private Long cnes;
	private String site;
	private Character prioridade;
	private String observacaoPrioridade;
	private Integer idClassificacaoPagamento;
	private String urlContrato;
	private Set<Prestador> prestadors = new HashSet<Prestador>(0);
	private Set<SxmlUsuario> sxmlUsuarios = new HashSet<SxmlUsuario>(0);
	private Set<Atendimento> atendimentos = new HashSet<Atendimento>(0);
	private PrestadorCadastrado prestadorCadastrado;
	private Set<SubProcesso> subProcessos = new HashSet<SubProcesso>(0);

	public Prestador() {
	}

	public Prestador(int idPrestador, char DTipoPessoa, String nome, Date dtCadastramento, char DTipoPrestador,
			boolean FIsentoIss, boolean FPagamentoSegueCronograma, boolean FEntregaNotaFiscal, boolean FCooperativa,
			Date timestamp) {
		this.idPrestador = idPrestador;
		this.DTipoPessoa = DTipoPessoa;
		this.nome = nome;
		this.dtCadastramento = dtCadastramento;
		this.DTipoPrestador = DTipoPrestador;
		this.FIsentoIss = FIsentoIss;
		this.FPagamentoSegueCronograma = FPagamentoSegueCronograma;
		this.FEntregaNotaFiscal = FEntregaNotaFiscal;
		this.FCooperativa = FCooperativa;
		this.timestamp = timestamp;
	}

	public Prestador(int idPrestador, Prestador prestador, char DTipoPessoa, String cpfCgc, String nome,
			Date dtCadastramento, String inss, String EMail, char DTipoPrestador, boolean FIsentoIss,
			boolean FPagamentoSegueCronograma, boolean FEntregaNotaFiscal, boolean FCooperativa, Date timestamp,
			Integer codPres, Long cnes, String site, Character prioridade, String observacaoPrioridade,
			Integer idClassificacaoPagamento, String urlContrato, Set<Prestador> prestadors,
			Set<SxmlUsuario> sxmlUsuarios, Set<Atendimento> atendimentos, PrestadorCadastrado prestadorCadastrado,
			Set<SubProcesso> subProcessos) {
		this.idPrestador = idPrestador;
		this.prestador = prestador;
		this.DTipoPessoa = DTipoPessoa;
		this.cpfCgc = cpfCgc;
		this.nome = nome;
		this.dtCadastramento = dtCadastramento;
		this.inss = inss;
		this.EMail = EMail;
		this.DTipoPrestador = DTipoPrestador;
		this.FIsentoIss = FIsentoIss;
		this.FPagamentoSegueCronograma = FPagamentoSegueCronograma;
		this.FEntregaNotaFiscal = FEntregaNotaFiscal;
		this.FCooperativa = FCooperativa;
		this.timestamp = timestamp;
		this.codPres = codPres;
		this.cnes = cnes;
		this.site = site;
		this.prioridade = prioridade;
		this.observacaoPrioridade = observacaoPrioridade;
		this.idClassificacaoPagamento = idClassificacaoPagamento;
		this.urlContrato = urlContrato;
		this.prestadors = prestadors;
		this.sxmlUsuarios = sxmlUsuarios;
		this.atendimentos = atendimentos;
		this.prestadorCadastrado = prestadorCadastrado;
		this.subProcessos = subProcessos;
	}

	@Id

	@Column(name = "id_prestador", unique = true, nullable = false)
	public int getIdPrestador() {
		return this.idPrestador;
	}

	public void setIdPrestador(int idPrestador) {
		this.idPrestador = idPrestador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestador_credenciado")
	public Prestador getPrestador() {
		return this.prestador;
	}

	public void setPrestador(Prestador prestador) {
		this.prestador = prestador;
	}

	@Column(name = "d_tipo_pessoa", nullable = false, length = 1)
	public char getDTipoPessoa() {
		return this.DTipoPessoa;
	}

	public void setDTipoPessoa(char DTipoPessoa) {
		this.DTipoPessoa = DTipoPessoa;
	}

	@Column(name = "cpf_cgc", length = 14)
	public String getCpfCgc() {
		return this.cpfCgc;
	}

	public void setCpfCgc(String cpfCgc) {
		this.cpfCgc = cpfCgc;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_cadastramento", nullable = false, length = 23)
	public Date getDtCadastramento() {
		return this.dtCadastramento;
	}

	public void setDtCadastramento(Date dtCadastramento) {
		this.dtCadastramento = dtCadastramento;
	}

	@Column(name = "inss", length = 11)
	public String getInss() {
		return this.inss;
	}

	public void setInss(String inss) {
		this.inss = inss;
	}

	@Column(name = "e_mail", length = 100)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "d_tipo_prestador", nullable = false, length = 1)
	public char getDTipoPrestador() {
		return this.DTipoPrestador;
	}

	public void setDTipoPrestador(char DTipoPrestador) {
		this.DTipoPrestador = DTipoPrestador;
	}

	@Column(name = "f_isento_iss", nullable = false)
	public boolean isFIsentoIss() {
		return this.FIsentoIss;
	}

	public void setFIsentoIss(boolean FIsentoIss) {
		this.FIsentoIss = FIsentoIss;
	}

	@Column(name = "f_pagamento_segue_cronograma", nullable = false)
	public boolean isFPagamentoSegueCronograma() {
		return this.FPagamentoSegueCronograma;
	}

	public void setFPagamentoSegueCronograma(boolean FPagamentoSegueCronograma) {
		this.FPagamentoSegueCronograma = FPagamentoSegueCronograma;
	}

	@Column(name = "f_entrega_nota_fiscal", nullable = false)
	public boolean isFEntregaNotaFiscal() {
		return this.FEntregaNotaFiscal;
	}

	public void setFEntregaNotaFiscal(boolean FEntregaNotaFiscal) {
		this.FEntregaNotaFiscal = FEntregaNotaFiscal;
	}

	@Column(name = "f_cooperativa", nullable = false)
	public boolean isFCooperativa() {
		return this.FCooperativa;
	}

	public void setFCooperativa(boolean FCooperativa) {
		this.FCooperativa = FCooperativa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "COD_PRES")
	public Integer getCodPres() {
		return this.codPres;
	}

	public void setCodPres(Integer codPres) {
		this.codPres = codPres;
	}

	@Column(name = "cnes", precision = 10, scale = 0)
	public Long getCnes() {
		return this.cnes;
	}

	public void setCnes(Long cnes) {
		this.cnes = cnes;
	}

	@Column(name = "site", length = 100)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "prioridade", length = 1)
	public Character getPrioridade() {
		return this.prioridade;
	}

	public void setPrioridade(Character prioridade) {
		this.prioridade = prioridade;
	}

	@Column(name = "observacao_prioridade")
	public String getObservacaoPrioridade() {
		return this.observacaoPrioridade;
	}

	public void setObservacaoPrioridade(String observacaoPrioridade) {
		this.observacaoPrioridade = observacaoPrioridade;
	}

	@Column(name = "id_classificacao_pagamento")
	public Integer getIdClassificacaoPagamento() {
		return this.idClassificacaoPagamento;
	}

	public void setIdClassificacaoPagamento(Integer idClassificacaoPagamento) {
		this.idClassificacaoPagamento = idClassificacaoPagamento;
	}

	@Column(name = "url_contrato", length = 8000)
	public String getUrlContrato() {
		return this.urlContrato;
	}

	public void setUrlContrato(String urlContrato) {
		this.urlContrato = urlContrato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestador")
	public Set<Prestador> getPrestadors() {
		return this.prestadors;
	}

	public void setPrestadors(Set<Prestador> prestadors) {
		this.prestadors = prestadors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestador")
	public Set<SxmlUsuario> getSxmlUsuarios() {
		return this.sxmlUsuarios;
	}

	public void setSxmlUsuarios(Set<SxmlUsuario> sxmlUsuarios) {
		this.sxmlUsuarios = sxmlUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestador")
	public Set<Atendimento> getAtendimentos() {
		return this.atendimentos;
	}

	public void setAtendimentos(Set<Atendimento> atendimentos) {
		this.atendimentos = atendimentos;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "prestador")
	public PrestadorCadastrado getPrestadorCadastrado() {
		return this.prestadorCadastrado;
	}

	public void setPrestadorCadastrado(PrestadorCadastrado prestadorCadastrado) {
		this.prestadorCadastrado = prestadorCadastrado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestador")
	public Set<SubProcesso> getSubProcessos() {
		return this.subProcessos;
	}

	public void setSubProcessos(Set<SubProcesso> subProcessos) {
		this.subProcessos = subProcessos;
	}

}
