package br.com.pojos;
// Generated 09/06/2016 17:56:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * GuiaConsulta generated by hbm2java
 */
@Entity
@Table(name = "GUIA_CONSULTA", schema = "dbo", catalog = "CacDb")
public class GuiaConsulta implements java.io.Serializable {

	private GuiaConsultaId id;
	private Date timestamp;
	private int idTipoSaida;
	private Date dtAtendimento;
	private Character DTipoDoenca;
	private Short tempoDoenca;
	private Character DUnidadeTempo;
	private Character DIndicacaoAcidente;
	private char DTipoConsulta;
	private String cidPrincipal;
	private String cid2;
	private String cid3;
	private String cid4;
	private String idNumeroGuiaPrestador;
	private Date dtEmissaoGuia;

	public GuiaConsulta() {
	}

	public GuiaConsulta(GuiaConsultaId id, int idTipoSaida, Date dtAtendimento, char DTipoConsulta) {
		this.id = id;
		this.idTipoSaida = idTipoSaida;
		this.dtAtendimento = dtAtendimento;
		this.DTipoConsulta = DTipoConsulta;
	}

	public GuiaConsulta(GuiaConsultaId id, int idTipoSaida, Date dtAtendimento, Character DTipoDoenca,
			Short tempoDoenca, Character DUnidadeTempo, Character DIndicacaoAcidente, char DTipoConsulta,
			String cidPrincipal, String cid2, String cid3, String cid4, String idNumeroGuiaPrestador,
			Date dtEmissaoGuia) {
		this.id = id;
		this.idTipoSaida = idTipoSaida;
		this.dtAtendimento = dtAtendimento;
		this.DTipoDoenca = DTipoDoenca;
		this.tempoDoenca = tempoDoenca;
		this.DUnidadeTempo = DUnidadeTempo;
		this.DIndicacaoAcidente = DIndicacaoAcidente;
		this.DTipoConsulta = DTipoConsulta;
		this.cidPrincipal = cidPrincipal;
		this.cid2 = cid2;
		this.cid3 = cid3;
		this.cid4 = cid4;
		this.idNumeroGuiaPrestador = idNumeroGuiaPrestador;
		this.dtEmissaoGuia = dtEmissaoGuia;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idGuiaConsulta", column = @Column(name = "id_guia_consulta", nullable = false)),
			@AttributeOverride(name = "idPessoa", column = @Column(name = "id_pessoa", nullable = false)) })
	public GuiaConsultaId getId() {
		return this.id;
	}

	public void setId(GuiaConsultaId id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "id_tipo_saida", nullable = false)
	public int getIdTipoSaida() {
		return this.idTipoSaida;
	}

	public void setIdTipoSaida(int idTipoSaida) {
		this.idTipoSaida = idTipoSaida;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_atendimento", nullable = false, length = 23)
	public Date getDtAtendimento() {
		return this.dtAtendimento;
	}

	public void setDtAtendimento(Date dtAtendimento) {
		this.dtAtendimento = dtAtendimento;
	}

	@Column(name = "d_tipo_doenca", length = 1)
	public Character getDTipoDoenca() {
		return this.DTipoDoenca;
	}

	public void setDTipoDoenca(Character DTipoDoenca) {
		this.DTipoDoenca = DTipoDoenca;
	}

	@Column(name = "tempo_doenca", precision = 3, scale = 0)
	public Short getTempoDoenca() {
		return this.tempoDoenca;
	}

	public void setTempoDoenca(Short tempoDoenca) {
		this.tempoDoenca = tempoDoenca;
	}

	@Column(name = "d_unidade_tempo", length = 1)
	public Character getDUnidadeTempo() {
		return this.DUnidadeTempo;
	}

	public void setDUnidadeTempo(Character DUnidadeTempo) {
		this.DUnidadeTempo = DUnidadeTempo;
	}

	@Column(name = "d_indicacao_acidente", length = 1)
	public Character getDIndicacaoAcidente() {
		return this.DIndicacaoAcidente;
	}

	public void setDIndicacaoAcidente(Character DIndicacaoAcidente) {
		this.DIndicacaoAcidente = DIndicacaoAcidente;
	}

	@Column(name = "d_tipo_consulta", nullable = false, length = 1)
	public char getDTipoConsulta() {
		return this.DTipoConsulta;
	}

	public void setDTipoConsulta(char DTipoConsulta) {
		this.DTipoConsulta = DTipoConsulta;
	}

	@Column(name = "cid_principal", length = 6)
	public String getCidPrincipal() {
		return this.cidPrincipal;
	}

	public void setCidPrincipal(String cidPrincipal) {
		this.cidPrincipal = cidPrincipal;
	}

	@Column(name = "cid_2", length = 6)
	public String getCid2() {
		return this.cid2;
	}

	public void setCid2(String cid2) {
		this.cid2 = cid2;
	}

	@Column(name = "cid_3", length = 6)
	public String getCid3() {
		return this.cid3;
	}

	public void setCid3(String cid3) {
		this.cid3 = cid3;
	}

	@Column(name = "cid_4", length = 6)
	public String getCid4() {
		return this.cid4;
	}

	public void setCid4(String cid4) {
		this.cid4 = cid4;
	}

	@Column(name = "id_numero_guia_prestador", length = 20)
	public String getIdNumeroGuiaPrestador() {
		return this.idNumeroGuiaPrestador;
	}

	public void setIdNumeroGuiaPrestador(String idNumeroGuiaPrestador) {
		this.idNumeroGuiaPrestador = idNumeroGuiaPrestador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_emissao_guia", length = 23)
	public Date getDtEmissaoGuia() {
		return this.dtEmissaoGuia;
	}

	public void setDtEmissaoGuia(Date dtEmissaoGuia) {
		this.dtEmissaoGuia = dtEmissaoGuia;
	}

}
