package br.com.pojos;
// Generated 09/06/2016 17:56:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GuiaConsultaId generated by hbm2java
 */
@Embeddable
public class GuiaConsultaId implements java.io.Serializable {

	private int idGuiaConsulta;
	private int idPessoa;

	public GuiaConsultaId() {
	}

	public GuiaConsultaId(int idGuiaConsulta, int idPessoa) {
		this.idGuiaConsulta = idGuiaConsulta;
		this.idPessoa = idPessoa;
	}

	@Column(name = "id_guia_consulta", nullable = false)
	public int getIdGuiaConsulta() {
		return this.idGuiaConsulta;
	}

	public void setIdGuiaConsulta(int idGuiaConsulta) {
		this.idGuiaConsulta = idGuiaConsulta;
	}

	@Column(name = "id_pessoa", nullable = false)
	public int getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(int idPessoa) {
		this.idPessoa = idPessoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GuiaConsultaId))
			return false;
		GuiaConsultaId castOther = (GuiaConsultaId) other;

		return (this.getIdGuiaConsulta() == castOther.getIdGuiaConsulta())
				&& (this.getIdPessoa() == castOther.getIdPessoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGuiaConsulta();
		result = 37 * result + this.getIdPessoa();
		return result;
	}

}
