package br.com.pojos;
// default package
// Generated 09/06/2016 15:23:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcessoId generated by hbm2java
 */
@Embeddable
public class ProcessoId implements java.io.Serializable {

	private int idProcesso;
	private short anoApresentacao;
	private int idRepresentacao;

	public ProcessoId() {
	}

	public ProcessoId(int idProcesso, short anoApresentacao, int idRepresentacao) {
		this.idProcesso = idProcesso;
		this.anoApresentacao = anoApresentacao;
		this.idRepresentacao = idRepresentacao;
	}

	@Column(name = "id_processo", nullable = false)
	public int getIdProcesso() {
		return this.idProcesso;
	}

	public void setIdProcesso(int idProcesso) {
		this.idProcesso = idProcesso;
	}

	@Column(name = "ano_apresentacao", nullable = false, precision = 4, scale = 0)
	public short getAnoApresentacao() {
		return this.anoApresentacao;
	}

	public void setAnoApresentacao(short anoApresentacao) {
		this.anoApresentacao = anoApresentacao;
	}

	@Column(name = "id_representacao", nullable = false)
	public int getIdRepresentacao() {
		return this.idRepresentacao;
	}

	public void setIdRepresentacao(int idRepresentacao) {
		this.idRepresentacao = idRepresentacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcessoId))
			return false;
		ProcessoId castOther = (ProcessoId) other;

		return (this.getIdProcesso() == castOther.getIdProcesso())
				&& (this.getAnoApresentacao() == castOther.getAnoApresentacao())
				&& (this.getIdRepresentacao() == castOther.getIdRepresentacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProcesso();
		result = 37 * result + this.getAnoApresentacao();
		result = 37 * result + this.getIdRepresentacao();
		return result;
	}

}
