package br.com.pojos;
// Generated 09/06/2016 17:56:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Processo generated by hbm2java
 */
@Entity
@Table(name = "PROCESSO", schema = "dbo", catalog = "CacDb")
public class Processo implements java.io.Serializable {

	private ProcessoId id;
	private Date timestamp;
	private Prestador prestador;
	private Date dthrApresentacao;
	private boolean FAnestesista;
	private Long numeroCarteira;
	private Double valorApresentado;
	private String amApres;
	private Integer codRepr;
	private Integer numProc;
	private Integer seqProc;
	private Set<SubProcesso> subProcessos = new HashSet<SubProcesso>(0);

	public Processo() {
	}

	public Processo(ProcessoId id, Date dthrApresentacao, boolean FAnestesista) {
		this.id = id;
		this.dthrApresentacao = dthrApresentacao;
		this.FAnestesista = FAnestesista;
	}

	public Processo(ProcessoId id, Prestador prestador, Date dthrApresentacao, boolean FAnestesista,
			Long numeroCarteira, Double valorApresentado, String amApres, Integer codRepr, Integer numProc,
			Integer seqProc, Set<SubProcesso> subProcessos) {
		this.id = id;
		this.prestador = prestador;
		this.dthrApresentacao = dthrApresentacao;
		this.FAnestesista = FAnestesista;
		this.numeroCarteira = numeroCarteira;
		this.valorApresentado = valorApresentado;
		this.amApres = amApres;
		this.codRepr = codRepr;
		this.numProc = numProc;
		this.seqProc = seqProc;
		this.subProcessos = subProcessos;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProcesso", column = @Column(name = "id_processo", nullable = false)),
			@AttributeOverride(name = "anoApresentacao", column = @Column(name = "ano_apresentacao", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "idRepresentacao", column = @Column(name = "id_representacao", nullable = false)) })
	public ProcessoId getId() {
		return this.id;
	}

	public void setId(ProcessoId id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestador")
	public Prestador getPrestador() {
		return this.prestador;
	}

	public void setPrestador(Prestador prestador) {
		this.prestador = prestador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dthr_apresentacao", nullable = false, length = 23)
	public Date getDthrApresentacao() {
		return this.dthrApresentacao;
	}

	public void setDthrApresentacao(Date dthrApresentacao) {
		this.dthrApresentacao = dthrApresentacao;
	}

	@Column(name = "f_anestesista", nullable = false)
	public boolean isFAnestesista() {
		return this.FAnestesista;
	}

	public void setFAnestesista(boolean FAnestesista) {
		this.FAnestesista = FAnestesista;
	}

	@Column(name = "numero_carteira", precision = 17, scale = 0)
	public Long getNumeroCarteira() {
		return this.numeroCarteira;
	}

	public void setNumeroCarteira(Long numeroCarteira) {
		this.numeroCarteira = numeroCarteira;
	}

	@Column(name = "valor_apresentado", precision = 53, scale = 0)
	public Double getValorApresentado() {
		return this.valorApresentado;
	}

	public void setValorApresentado(Double valorApresentado) {
		this.valorApresentado = valorApresentado;
	}

	@Column(name = "am_apres", length = 4)
	public String getAmApres() {
		return this.amApres;
	}

	public void setAmApres(String amApres) {
		this.amApres = amApres;
	}

	@Column(name = "cod_repr")
	public Integer getCodRepr() {
		return this.codRepr;
	}

	public void setCodRepr(Integer codRepr) {
		this.codRepr = codRepr;
	}

	@Column(name = "num_proc")
	public Integer getNumProc() {
		return this.numProc;
	}

	public void setNumProc(Integer numProc) {
		this.numProc = numProc;
	}

	@Column(name = "seq_proc")
	public Integer getSeqProc() {
		return this.seqProc;
	}

	public void setSeqProc(Integer seqProc) {
		this.seqProc = seqProc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processo")
	public Set<SubProcesso> getSubProcessos() {
		return this.subProcessos;
	}

	public void setSubProcessos(Set<SubProcesso> subProcessos) {
		this.subProcessos = subProcessos;
	}

}
