package br.com.pojos;
// Generated 09/06/2016 17:56:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SxmlProtocoloProcessoId generated by hbm2java
 */
@Embeddable
public class SxmlProtocoloProcessoId implements java.io.Serializable {

	private int idProcesso;
	private short anoApresentacao;
	private int idRepresentacao;
	private char DSubProcesso;
	private char DNatureza;
	private byte idSequencialNatureza;
	private long idProtocolo;

	public SxmlProtocoloProcessoId() {
	}

	public SxmlProtocoloProcessoId(int idProcesso, short anoApresentacao, int idRepresentacao, char DSubProcesso,
			char DNatureza, byte idSequencialNatureza, long idProtocolo) {
		this.idProcesso = idProcesso;
		this.anoApresentacao = anoApresentacao;
		this.idRepresentacao = idRepresentacao;
		this.DSubProcesso = DSubProcesso;
		this.DNatureza = DNatureza;
		this.idSequencialNatureza = idSequencialNatureza;
		this.idProtocolo = idProtocolo;
	}

	@Column(name = "id_processo", nullable = false)
	public int getIdProcesso() {
		return this.idProcesso;
	}

	public void setIdProcesso(int idProcesso) {
		this.idProcesso = idProcesso;
	}

	@Column(name = "ano_apresentacao", nullable = false, precision = 4, scale = 0)
	public short getAnoApresentacao() {
		return this.anoApresentacao;
	}

	public void setAnoApresentacao(short anoApresentacao) {
		this.anoApresentacao = anoApresentacao;
	}

	@Column(name = "id_representacao", nullable = false)
	public int getIdRepresentacao() {
		return this.idRepresentacao;
	}

	public void setIdRepresentacao(int idRepresentacao) {
		this.idRepresentacao = idRepresentacao;
	}

	@Column(name = "d_sub_processo", nullable = false, length = 1)
	public char getDSubProcesso() {
		return this.DSubProcesso;
	}

	public void setDSubProcesso(char DSubProcesso) {
		this.DSubProcesso = DSubProcesso;
	}

	@Column(name = "d_natureza", nullable = false, length = 1)
	public char getDNatureza() {
		return this.DNatureza;
	}

	public void setDNatureza(char DNatureza) {
		this.DNatureza = DNatureza;
	}

	@Column(name = "id_sequencial_natureza", nullable = false)
	public byte getIdSequencialNatureza() {
		return this.idSequencialNatureza;
	}

	public void setIdSequencialNatureza(byte idSequencialNatureza) {
		this.idSequencialNatureza = idSequencialNatureza;
	}

	@Column(name = "id_protocolo", nullable = false, precision = 18, scale = 0)
	public long getIdProtocolo() {
		return this.idProtocolo;
	}

	public void setIdProtocolo(long idProtocolo) {
		this.idProtocolo = idProtocolo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SxmlProtocoloProcessoId))
			return false;
		SxmlProtocoloProcessoId castOther = (SxmlProtocoloProcessoId) other;

		return (this.getIdProcesso() == castOther.getIdProcesso())
				&& (this.getAnoApresentacao() == castOther.getAnoApresentacao())
				&& (this.getIdRepresentacao() == castOther.getIdRepresentacao())
				&& (this.getDSubProcesso() == castOther.getDSubProcesso())
				&& (this.getDNatureza() == castOther.getDNatureza())
				&& (this.getIdSequencialNatureza() == castOther.getIdSequencialNatureza())
				&& (this.getIdProtocolo() == castOther.getIdProtocolo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProcesso();
		result = 37 * result + this.getAnoApresentacao();
		result = 37 * result + this.getIdRepresentacao();
		result = 37 * result + this.getDSubProcesso();
		result = 37 * result + this.getDNatureza();
		result = 37 * result + this.getIdSequencialNatureza();
		result = 37 * result + (int) this.getIdProtocolo();
		return result;
	}

}
