package br.com.pojos;
// Generated 09/06/2016 17:56:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SxmlProtocoloProcesso generated by hbm2java
 */
@Entity
@Table(name = "SXML_PROTOCOLO_PROCESSO", schema = "dbo", catalog = "CacDb")
public class SxmlProtocoloProcesso implements java.io.Serializable {

	private SxmlProtocoloProcessoId id;
	private Date timestamp;
	private SubProcesso subProcesso;

	public SxmlProtocoloProcesso() {
	}

	public SxmlProtocoloProcesso(SxmlProtocoloProcessoId id, SubProcesso subProcesso) {
		this.id = id;
		this.subProcesso = subProcesso;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idProcesso", column = @Column(name = "id_processo", nullable = false)),
			@AttributeOverride(name = "anoApresentacao", column = @Column(name = "ano_apresentacao", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "idRepresentacao", column = @Column(name = "id_representacao", nullable = false)),
			@AttributeOverride(name = "DSubProcesso", column = @Column(name = "d_sub_processo", nullable = false, length = 1)),
			@AttributeOverride(name = "DNatureza", column = @Column(name = "d_natureza", nullable = false, length = 1)),
			@AttributeOverride(name = "idSequencialNatureza", column = @Column(name = "id_sequencial_natureza", nullable = false)),
			@AttributeOverride(name = "idProtocolo", column = @Column(name = "id_protocolo", nullable = false, precision = 18, scale = 0)) })
	public SxmlProtocoloProcessoId getId() {
		return this.id;
	}

	public void setId(SxmlProtocoloProcessoId id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "id_processo", referencedColumnName = "id_processo", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ano_apresentacao", referencedColumnName = "ano_apresentacao", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "id_representacao", referencedColumnName = "id_representacao", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "d_sub_processo", referencedColumnName = "d_sub_processo", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "d_natureza", referencedColumnName = "d_natureza", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "id_sequencial_natureza", referencedColumnName = "id_sequencial_natureza", nullable = false, insertable = false, updatable = false) })
	public SubProcesso getSubProcesso() {
		return this.subProcesso;
	}

	public void setSubProcesso(SubProcesso subProcesso) {
		this.subProcesso = subProcesso;
	}

}
